### PR TITLE
Add more data

### PR DESCRIPTION
**Pull request by cebe**
added a bunch of pages for more ICU data

bildschirmfoto von 2016-03-02 19 05 54
bildschirmfoto von 2016-03-02 19 05 34
bildschirmfoto von 2016-03-02 19 05 20

### CODE REVIEW

**Comment by samdark** [comment]
Thanks! It's not part of the master.

**Comment by samdark** [comment]
http://intl.rmcreative.ru/tables?locale=de_DE

**Comment by cebe** [comment]
> not part of the master.

now? :)

**Comment by samdark** [comment]
Yes :)

**Pull request closed without merging**
